/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AzResume {
    'showDownloadLink': boolean;
  }
  interface SvgIcon {
    'name': string;
    'small': boolean;
  }
}

declare global {


  interface HTMLAzResumeElement extends Components.AzResume, HTMLStencilElement {}
  var HTMLAzResumeElement: {
    prototype: HTMLAzResumeElement;
    new (): HTMLAzResumeElement;
  };

  interface HTMLSvgIconElement extends Components.SvgIcon, HTMLStencilElement {}
  var HTMLSvgIconElement: {
    prototype: HTMLSvgIconElement;
    new (): HTMLSvgIconElement;
  };
  interface HTMLElementTagNameMap {
    'az-resume': HTMLAzResumeElement;
    'svg-icon': HTMLSvgIconElement;
  }
}

declare namespace LocalJSX {
  interface AzResume {
    'showDownloadLink'?: boolean;
  }
  interface SvgIcon {
    'name'?: string;
    'small'?: boolean;
  }

  interface IntrinsicElements {
    'az-resume': AzResume;
    'svg-icon': SvgIcon;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'az-resume': LocalJSX.AzResume & JSXBase.HTMLAttributes<HTMLAzResumeElement>;
      'svg-icon': LocalJSX.SvgIcon & JSXBase.HTMLAttributes<HTMLSvgIconElement>;
    }
  }
}


